### PR TITLE
RichardsVarNames now uses coupledNodalValue.  RichardsPiecewiseLinearSin...

### PR DESCRIPTION
**Pull request by WilkAndy**
...k, RichardsBorehole, RichardsFullyUpwindFlux, RichardsLumpedMassChange altered to use this.  (Note that RichardsMaterial does not use this, but still calculates things at quadpoints, even if only nodal quantities are required by BCs, Kernels, etc.  I need to refactor this stuff and include a new nodal-only Material, I think.)  #4038

### CODE REVIEW

**Comment by andrsd** [comment]
You have got some print statements that were not there before. We typically do not do that. Do you want them in the final version?

I can merge this as it is right now and we can polish the branch before we make an PR to MOOSE. It is up to you how you want to proceed.

Also, I think I know how to do the DiracKernel stuff now, but I can get to it the next week.

**Comment by WilkAndy** [comment]
Drat, @andrsd , i don't want those dumb print statements, please remove them !

a

**Comment by WilkAndy** [comment]
By the way, I'm happy how this all works.  I've got some time today.  Please tell me if I need to do anything to make this OK for MOOASE.

a

**Comment by andrsd** [comment]
> please remove them !

No problem, I'll do it.

We just needed to try this out, if it is doing the right thing. Now, that we know it does, to move forward, I need to make nodal values available in dirac kernels and then you need to update your code to drop that workaround. Then we will rebase and polish up this branch and merge it. Easy stuff ;-)

**Comment by WilkAndy** [comment]
Hey @andrsd , I'm not really sure what you mean by my "workaround" in the DiracKernel case.  I just get the nodal values like I do in the Kernel case and it all seems to work fine.  Am I dreaming?

a

**Comment by andrsd** [comment]
I did not know the values were available there. I thought it needed some extra work, so let me check that the right things are happening and you are not getting lucky and grabbing some left-over values.

**Comment by WilkAndy** [comment]
Thanks @andrsd

**Pull request merged**
